### ISSUE TITLE
Imported resource (image) could not be downloaded from external resource due to timeout or access permissions

### ISSUE THREAD

**Issue by mattiaguatta** [firegento/FireGento_ExtendedImport2#45] opened 2023-06-20 08:39 UTC
hello,

i uploaded an image on pub/media/import/ but still have this error on magento 2.4.5, any solutions?

thanks

**Comment by sprankhub** [comment] 2023-06-20 09:00
Duplicate of https://github.com/firegento/FireGento_FastSimpleImport2/issues/139.

**Closed as completed by sprankhub** 2023-06-20 09:00 UTC
